version: '2'
services:
  yamlparse_tester:
    container_name: yamlparse_tester
    image: scwhitin/yamlparse_tester
    restart: unless-stopped
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.yamlparse_tester.rule=Host(`yamlpath-tester.scwhitin.com`)"
     - "traefik.http.services.yamlparse_tester.loadbalancer.server.port=80"
     - "traefik.http.routers.yamlparse_tester.entrypoints=https"
     - "traefik.http.routers.yamlparse_tester.tls=true"
networks:
 default:
  external:
   name: flat_net